WorldLib/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WorldLib.Enums;
using WorldLib.Models;
using WorldLib.Services;

namespace WorldLib.Controllers
{
    public class RecipeController : Controller
    {
        // GET: Recipe
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetCategories()     
        {
            var model = RecipeViewModel.Load();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CreateComment(int recipeId, string text)
        {
            var rep = new Repository<RecipeComment>();
            var comment = new RecipeComment
            {
                RecipeId = recipeId,
                Text = text,
                CreateDateTime = DateTime.Now,
                Status = CommentStatusEnum.Moderation,
                UserId =  HttpContext.User.Identity.GetUserId()
            };
            rep.Create(comment);
            rep.Commit();
            return Json("Комментарий будет добавлен после успешной модерации", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetCommentsByRecipeId(int recipeId)
        {
            var model = RecipeCommentViewModel.Load(recipeId);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

WorldLib/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @using WorldLib.Enums
    

</head>
<body style="background-color: #78909c; background-image: url(/Content/Images/moloko_kuvshin_hleb_bulochki_korzina_pomidory_luk_pshenica_pole_nebo_76706_1280x960.jpg); background-size: auto;">
    @*background-attachment:fixed;*@
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Кулинария", "Index", "Recipe", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Администрирование", "Index", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding-top: 12px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/knockout-3.4.2.js")
    @*<script data-main="~/Scripts/config.js" src="~/Scripts/require.js"></script>*@
    @RenderSection("scripts", required: false)
    @*@RenderSection("require", required: true)*@

</body>
</html>